This is makeindex.exe, version 2.15 [MiKTeX 2.9] (kpathsea + Thai support).
Scanning style file C:/Users/yanson/Documents/Memoire - Copie/Memoire.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file Memoire.acn....done (36 entries accepted, 0 rejected).
Sorting entries....done (192 comparisons).
Generating output file Memoire.acr....done (31 lines written, 0 warnings).
Output written in Memoire.acr.
Transcript written in Memoire.alg.
